name: Security Audit

on:
  push:
    paths:
      # Run if workflow changes
      - '.github/workflows/security.yml'
      # Run on changed dependencies
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  # Rerun periodically to pick up new advisories
  schedule:
    - cron: '0 0 * * *'
  # Run manually
  workflow_dispatch:

jobs:
  audit:
    name: Audit Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run audit check
        # Ignored until https://github.com/apache/datafusion/issues/15571
        # ignored py03 warning until arrow 55 upgrade
        run: cargo audit --ignore RUSTSEC-2024-0370 --ignore RUSTSEC-2025-0020
